In [27]:
print("This model is meant to be run exclusively on CPU, not GPU using cuda. The changes are not drastic though to switch between the two, they require some conditional logic and pushing the parameters to device, but nothing huge. Loss is only calculated once, not averaged, this is a necessary optimization though")
print("This model is decoder only, so lacks encoder part of Attention is all you need paper, and lacks cross-attention")
print("This model is just a document completer, not a question answerer: need to fine-tune beyond the pretraining here to accomplish this")

This model is meant to be run exclusively on CPU, not GPU using cuda. The changes are not drastic though to switch between the two, they require some conditional logic and pushing the parameters to device, but nothing huge. Loss is only calculated once, not averaged, this is a necessary optimization though
This model is decoder only, so lacks encoder part of Attention is all you need paper, and lacks cross-attention
This model is just a document completer, not a question answerer: need to fine-tune beyond the pretraining here to accomplish this


In [28]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [29]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [30]:
enc = {ch:i for i, ch in enumerate(chars)} #iterators via enumerate
dec = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [enc[c] for c in s] #serves as our encoder to convert characters in a sequence to list of numbers
decode = lambda l: ''.join([dec[i] for i in l]) #conv list of integers into a string (decoder)
print(encode("hii there"))
print(decode(encode("hii there")))
#conversion both ways complete

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [31]:
print("above is a character level tokenizer scheme, small vocab of only 65 letters in the shakespeare dataset: but can use tiktoken by openAI or sentencepiece by google to create a more robust encoder/decoder scheme")

above is a character level tokenizer scheme, small vocab of only 65 letters in the shakespeare dataset: but can use tiktoken by openAI or sentencepiece by google to create a more robust encoder/decoder scheme


In [32]:
import torch
data = torch.tensor(encode(text), dtype = torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [33]:
#create a couple global vars for rest of book
n_embd = 64
dropout = 0.2
#number of embedding dimensions

In [34]:
cutoff = int(0.9*len(data))
train = data[:cutoff]
val = data[cutoff:]

In [35]:
context_window = 32
train[:context_window+1] #to enable offsets for prediction/target

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1])

In [36]:
x = train[:context_window]
y = train[1:context_window+1]
for i in range(context_window):
    context = x[:i+1]
    target = y[i]
    print(f"input {context} target {target}")
print("trains context length times with varying context lengths from 1 to context length for training efficiency, but inference will be less efficient off many softmax PD predictions going to 'waste' for inference use case")

input tensor([18]) target 47
input tensor([18, 47]) target 56
input tensor([18, 47, 56]) target 57
input tensor([18, 47, 56, 57]) target 58
input tensor([18, 47, 56, 57, 58]) target 1
input tensor([18, 47, 56, 57, 58,  1]) target 15
input tensor([18, 47, 56, 57, 58,  1, 15]) target 47
input tensor([18, 47, 56, 57, 58,  1, 15, 47]) target 58
input tensor([18, 47, 56, 57, 58,  1, 15, 47, 58]) target 47
input tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47]) target 64
input tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64]) target 43
input tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43]) target 52
input tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52]) target 10
input tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10]) target 0
input tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0]) target 14
input tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14]) target 43
input tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 

In [37]:
#batching for parallelization
torch.manual_seed(1337)
batchsize = 16 #num parallel sequences being processed
cwbatch = 32 #context window max len
def get_batch(splitname):
    #create batches of data
    data = train if splitname == "train" else val
    idx = torch.randint(len(data) - cwbatch, (batchsize,))
    x =  torch.stack([data[i:i+cwbatch] for i in idx])
    y = torch.stack([data[i+1:i+1+cwbatch] for i in idx])
    return x, y
xbatch, ybatch = get_batch('train')
print("inputs:")
print(xbatch.shape)
print(xbatch)
print("targets:")
print(ybatch.shape)
print(ybatch)

print("______")
for b in range(batchsize):
    for t in range(cwbatch):
        context = xbatch[b:t+1]
        target = ybatch[b, t]
        print(f"input: {context.tolist()} target: {target}")

inputs:
torch.Size([16, 32])
tensor([[58, 53,  1, 41, 53, 56, 56, 59, 54, 58,  1, 39,  1, 51, 39, 52,  5, 57,
          1, 61, 47, 44, 43,  1, 47, 57,  0, 61, 46, 43, 52,  1],
        [49,  1, 39, 52,  1, 53, 39, 58, 46,  1, 40, 63,  1, 20, 47, 51,  6,  0,
         32, 46, 43,  1, 59, 52, 47, 58, 63,  1, 58, 46, 43,  1],
        [59, 50, 42,  1, 58, 46, 53, 59,  1, 61, 43, 56, 58,  1, 57, 53,  1, 58,
         53, 53,  2,  0,  0, 24, 33, 15, 21, 27, 10,  0, 35, 43],
        [ 8,  0,  0, 35, 13, 30, 35, 21, 15, 23, 10,  0, 28, 56, 53, 60, 43,  1,
         47, 58,  6,  1, 20, 43, 52, 56, 63,  6,  1, 39, 52, 42],
        [58,  1, 57, 46, 43,  8,  0,  0, 32, 30, 13, 26, 21, 27, 10,  0, 18, 53,
         56,  1, 61, 46, 39, 58,  1, 56, 43, 39, 57, 53, 52,  6],
        [56, 61, 47, 41, 49,  6,  1, 50, 43, 58,  1, 47, 58,  1, 40, 43, 11,  0,
         18, 53, 56,  1, 47, 52,  1, 58, 46, 63,  1, 57, 46, 53],
        [25, 10,  0, 35, 47, 58, 46, 42, 56, 39, 61,  1, 63, 53, 59,  1, 46, 43,
        

In [38]:
class LayerNorm1d: # (copy pasted, normalizes rows instead of columns as in BatchNorm)
  
  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)
  
  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out
  
  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [39]:
#create bigram lm
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)
class Head(nn.Module):
    #one head of self attention
    def __init__(self, head_size):
        super().__init__()
        self.query = nn.Linear(n_embd, head_size, bias = False)
        self.key = nn.Linear(n_embd, head_size, bias = False)
        self.value = nn.Linear(n_embd, head_size, bias = False)
        self.register_buffer('tril', torch.tril(torch.ones(context_window, context_window)))
        self.dropout = nn.Dropout(dropout)
    '''B, T, C = 4, 8, 32 #batch, time, channels - 4 by 8 arrangement of tokens and each token is currently 32 dimenisional
    #x = torch.randn(B, T, C)

    #single attention head
    head_size = 16
    query = nn.Linear(C, head_size, bias = False)
    key = nn.Linear(C, head_size, bias = False)
    value = nn.Linear(C, head_size, bias = False)

    #tril = torch.tril(torch.ones(T, T))
    #wei = torch.zeros((T, T))

    the following line is very important. in autoregressive settings like LLMS, you mask future tokens from being used in the
    context of a previous token. Hence why the masked fill line is present. In cases like sentiment
    analysis, you may not want information to be masked, and rather have every token talk to every other
    token in the sequence, so you would just delete the directly following masked fill line. 
    The autoregressive method with masked fill is known as a decoder attention block, sentiment like 
    full context without traingular masking is known as an encoder attention block
    wei = wei.masked_fill(tril == 0, float('-inf'))


    wei - F.softmax(wei, dim = -1)
    v = value(x)
    out = wei @ v
    #out = wei @ x
    out.shape'''
    def forward(self,x):
        B,T,C = x.shape
        k = self.key(x) #(B, T, 16) where 16 is head size aka B, T, C
        q = self.query(x) #(B, T, 16)
        wei = q @ k.transpose(-2, -1) * C**-0.5 #only transpose the last two since we need the B vector, normalize it
        #--> (B, T, 16) @ (B, 16, T) --> (B, T, T) (makes the weights data dependent and not just uniform)
        '''the following line is very important. in autoregressive settings like LLMS, you mask future tokens from being used in the
        context of a previous token. Hence why the masked fill line is present. In cases like sentiment
        analysis, you may not want information to be masked, and rather have every token talk to every other
        token in the sequence, so you would just delete the directly following masked fill line. 
        The autoregressive method with masked fill is known as a decoder attention block, sentiment like 
        full context without traingular masking is known as an encoder attention block'''
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim = -1) #(B, T, T)
        wei = self.dropout(wei)
        v = self.value(x)
        out = wei @ v
        return out  
class MultiHeadAttention(nn.Module):
    #multiple self-attention heads running in parallel
    def __init__(self, num_heads, head_size):
        super().__init__()        
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd) #linear transformation of the outcome of the concatennation within MHA
        self.dropout = nn.Dropout(dropout)
    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim = -1) #concatenate results of the parallelly running attention heads over the channel dimension
        out = self.dropout(self.proj(out))
        return out
class FeedForward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd), #4 multiplied pursuant to the original Attnetion is all you need paper 512 --> 2048 --> 512
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd), #residual layer
            nn.Dropout(dropout)
        )
    def forward(self, x):
        return self.net(x)
class Block(nn.Module):
    #communication then computation
    def __init__(self, n_embd, n_head):
        #n_head = number of heads we want
        super().__init__()
        head_size = n_embd //n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)
    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x
class BigramLM(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd) #create a vocab by vocab sized embedding table - each token reads off the logits for the following token based on this table
        #box 1: token encoding is complete, now box2: positional encoddings
        self.position_embedding_table = nn.Embedding(context_window, n_embd)
        self.blocks = nn.Sequential(
            Block(n_embd, n_head=4),
            Block(n_embd, n_head=4),
            Block(n_embd, n_head=4),
            nn.LayerNorm(n_embd)
        )
        #self.selfattentionhead = MultiHeadAttention(4, n_embd//4) #4 heads of 8-dimensional self-attention
        #self.ffwd = FeedForward(n_embd)
        self.languagemodellinghead = nn.Linear(n_embd, vocab_size)
    def forward(self, idx, targets=None):
        #idx and targets are both (B, T) tensor of integers
        B, T = idx.shape
        
        token_embeddings = self.token_embedding_table(idx) #(Batch, Time, Channel) AKA B,T,C where B = batchsize (4), T = cwbatch = context window = 8, channel = vocab_size (65)
        positional_embeddings = self.position_embedding_table(torch.arange(T))
        x = token_embeddings + positional_embeddings  #(B, T, C)
        #x = self.selfattentionhead(x) #apply one head of self-attention outputting answer in format (B,T,C)
        #x = self.ffwd(x) #(B, T, C)
        x = self.blocks(x) #(B, T, C)
        logits = self.languagemodellinghead(x) #(B, T, vocabsize) - this step applies the decoder language model we have to create logits from the output of the previous line
        if targets is None: #optional to syncronize with the generate call through self (self in genertate calls forward)
            loss = None
        else:
            B,T,C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            #merge B and T dimensions into one dimensional vector in order to match pytorch requirement for C to be the second parameter for the cross entropy fn
            loss = F.cross_entropy(logits, targets) #assess accuracy of logits (predictions) relative to the targets - correct dimension of logits should be a high number, rest very low number (essentaily unnormalized prob dists.)
        return logits, loss
    def generate(self, idx, max_new_tokens):
        #idx is (B,T) array of indicies here - represents the current context of some characters in some batch
        #generates one by one increase in tokens and appends this to the running sequence - go from B x T to B x T + 1, B x T + 2
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -batchsize:] #crop idx to the last batch_size number of tokens to ensure positional encodings are within rangae
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :] #only last time step to become (B, C)
            probs = F.softmax(logits, dim = -1) #softmax --> prb dist. (B, C)
            idx_next = torch.multinomial(probs, num_samples = 1) #(B, 1 - single prediction for what comes next in each of the batch dimensions)
            idx = torch.cat((idx, idx_next), dim = 1) #(B, T+1) #extra for bigram model since that relies on prev token prediction and this concatenation 
            #passes in the entire accumulated string into the model each time to predict the next token, but this generate function is meant to be generalizable 
            #to different models that want/require more context than just the preceding character to predict the next character (can swap character/token here depending on tokenization scheme used)

        return idx
m = BigramLM(vocab_size)
logits, loss = m(xbatch, ybatch)
print(logits.shape)
print(loss)
print("expected loss for negative log likelihood of -ln(1/65) ~ 4.17")
#generates logits (scores) for every one of the 4 by 8 positions

# idx portion: batch and time are 1 --> tensor is 1 x 1 and holdds a 0. 0 kicks off the generation (represents new line char)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype = torch.long), max_new_tokens = 100)[0].tolist())) #indexing into 0th row indexes into the single batch dimension that exists

torch.Size([512, 65])
tensor(4.3938, grad_fn=<NllLossBackward0>)
expected loss for negative log likelihood of -ln(1/65) ~ 4.17

OoxJckvQr;KYRsUvguREZuJsRpoQ$Cpc;?I,gt$XfT&AIZ-YXKSgCnqqH'v.zGL&SgWs-WUaEYdpCC-sPcgLd&ALHSx
$TdUzXWN


In [40]:
#create optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr = 1e-3)

In [41]:
batch_size = 32 #update to be bigger
for steps in range(5000):
    xbatch, ybatch = get_batch('train')
    logits, loss = m(xbatch, ybatch)
    optimizer.zero_grad(set_to_none = True) #zero out gradients from the previous step 
    loss.backward() #get those gradients for all the parameters
    optimizer.step() #using the gradients to update the parameters

print(loss.item())

1.8349865674972534


In [42]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype = torch.long), max_new_tokens = 2000)[0].tolist())) #indexing into 0th row indexes into the single batch dimension that exists


Terel, and spyrosee,
Stice; Good noblows.

HENRENCENIA:
Aborth am arge all
'twen
Th do time bleaid they to thear anots fear grongo artuee so Which beKet heard
Abod, in shellem caulude so deednor black'd a not consumaned thy pon you he omess,
I came of thy bife sagains copon.

GLORAS:
Tere thy lest:
His dotbalow outh This; what to defor up opusiness.
You as to live bawbroys,
When him torms: in prie if's propars the can.'
AULIET:
Edwas sir, the peake rove me servenge I head tell be to timase, you was it belinemmern'd earthing they, you look you, sworn.
He lory inclunes;
Troy, it wity fortund harts highter of lovess;
Dylorous, were entemice me, it? we trom came a wret convuse.
To king, for, the pershalds.

HEROS:
Eollow, live, ar saidlenter lattected, if hir spould bady prone'
To fedraw he good?

NORTES:
What thy lise, and be Comes torse in man thy look on eginguice? Henrest me here say;
That the boatt pity
all madteran, if a heavise slarcan hunstraring heart and set ruender an ceac they

In [43]:
#masked self attention below

In [44]:
 #v1
B, T, C = 4, 8 , 2
x = torch.randn(B, T, C)
xbagofwords = torch.zeros((B, T, C))
for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1] # shape (t,C)
        xbagofwords[b, t] = torch.mean(xprev, 0)
#simple averaging C over all prev words - not effective since very lossy, and inefficient without matrix math
x[0]

tensor([[-0.7096,  0.1019],
        [ 0.9291, -0.2172],
        [-0.4148, -1.4352],
        [ 0.2320, -0.3620],
        [-0.7372,  0.3619],
        [ 0.4320, -2.2656],
        [-0.5795,  0.5560],
        [-1.3687, -0.7327]])

In [45]:
xbagofwords[0]
#average of all previous moving down

tensor([[-0.7096,  0.1019],
        [ 0.1097, -0.0576],
        [-0.0651, -0.5168],
        [ 0.0092, -0.4781],
        [-0.1401, -0.3101],
        [-0.0448, -0.6360],
        [-0.1212, -0.4657],
        [-0.2771, -0.4991]])

In [46]:
#v2
weights = torch.tril(torch.ones(T, T))
#create triangular matrix for averaging in conjunction with next step
weights = weights/weights.sum(1, keepdim = True)  #rows sum to 1
weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [47]:
xbagofwords2 = weights @ x #(T,T) @ (B, T, C) --> pytorch will add a batch dimension (B, T, T) @ (B, T, C) --> (B, T, C)
torch.allclose(xbagofwords, xbagofwords2) #now will be the same after the prev step

True

In [48]:
 #v3 using softmax
tril = torch.tril(torch.ones(T, T)) #lower triangular matrix of 1s
weights = torch.zeros((T, T)) #all 0s initially
weights = weights.masked_fill(tril == 0, float('-inf')) #assign tril 0s to be - infinity
weights = F.softmax(weights, dim = -1) #take softmax along every single row - normalizes and spits back the same matrix for xbagofwords and xbagofwords3
xbagofwords3 = weights @ x
torch.allclose(xbagofwords, xbagofwords3)
#this is the preferred version for self-attention since the pd generated by the softmax demonstartes impact of certain tokens communicating with others to influence their context
#the weights are data-dependent, goes to the Q, K, V, context-rich vector mechanisms in the multihead triangularly masked self attention mechanism



True

In [49]:
#v4: self attention
'''torch.manual_seed(1337)
class Head(nn.Module):
    #one head of self attention
    def __init__(self, head_size):
        super().__init__()
        self.query = nn.Linear(n_embd, head_size, bias = False)
        self.key = nn.Linear(n_embd, head_size, bias = False)
        self.value = nn.Linear(n_embd, head_size, bias = False)
        self.register_buffer('tril', torch.tril(torch.ones(batch_size, batch_size)))'''
'''B, T, C = 4, 8, 32 #batch, time, channels - 4 by 8 arrangement of tokens and each token is currently 32 dimenisional
#x = torch.randn(B, T, C)

#single attention head
head_size = 16
query = nn.Linear(C, head_size, bias = False)
key = nn.Linear(C, head_size, bias = False)
value = nn.Linear(C, head_size, bias = False)

#tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T, T))

the following line is very important. in autoregressive settings like LLMS, you mask future tokens from being used in the
context of a previous token. Hence why the masked fill line is present. In cases like sentiment
analysis, you may not want information to be masked, and rather have every token talk to every other
token in the sequence, so you would just delete the directly following masked fill line. 
The autoregressive method with masked fill is known as a decoder attention block, sentiment like 
full context without traingular masking is known as an encoder attention block
wei = wei.masked_fill(tril == 0, float('-inf'))


wei - F.softmax(wei, dim = -1)
v = value(x)
out = wei @ v
#out = wei @ x
out.shape'''
'''def forward(self,x):
    B,T,C = x.shape
    k = self.key(x) #(B, T, 16) where 16 is head size aka B, T, C
    q = self.query(x) #(B, T, 16)
    wei = q @ k.transpose(-2, -1) * C**-0.5 #only transpose the last two since we need the B vector, normalize it
#--> (B, T, 16) @ (B, 16, T) --> (B, T, T) (makes the weights data dependent and not just uniform)
    the following line is very important. in autoregressive settings like LLMS, you mask future tokens from being used in the
    context of a previous token. Hence why the masked fill line is present. In cases like sentiment
    analysis, you may not want information to be masked, and rather have every token talk to every other
    token in the sequence, so you would just delete the directly following masked fill line. 
    The autoregressive method with masked fill is known as a decoder attention block, sentiment like 
    full context without traingular masking is known as an encoder attention block
    wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
    wei = F.softmax(wei, dim = -1) #(B, T, T)
    v = self.value(x)
    out = wei @ v
    return out  '''
    

"def forward(self,x):\n    B,T,C = x.shape\n    k = self.key(x) #(B, T, 16) where 16 is head size aka B, T, C\n    q = self.query(x) #(B, T, 16)\n    wei = q @ k.transpose(-2, -1) * C**-0.5 #only transpose the last two since we need the B vector, normalize it\n#--> (B, T, 16) @ (B, 16, T) --> (B, T, T) (makes the weights data dependent and not just uniform)\n    the following line is very important. in autoregressive settings like LLMS, you mask future tokens from being used in the\n    context of a previous token. Hence why the masked fill line is present. In cases like sentiment\n    analysis, you may not want information to be masked, and rather have every token talk to every other\n    token in the sequence, so you would just delete the directly following masked fill line. \n    The autoregressive method with masked fill is known as a decoder attention block, sentiment like \n    full context without traingular masking is known as an encoder attention block\n    wei = wei.masked_fi

In [50]:
model = BigramLM(vocab_size)
print(sum(p.numel() for p in model.parameters()))

159937
